[package]
name = "chunkfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chunking = { git = "https://github.com/Piletskii-Oleg/rust-chunking.git" }
rand = "0.8.5"

[profile.release-deb]
inherits = "release"
debug = true
